### ISSUE TITLE
Need of signature mechanism into the safe apps

### ISSUE THREAD

**Issue by vrolland** [gnosis/safe-apps-sdk#10]
Hello guys, Great job!

I am currently creating a safe app for Request.

For our use case, we need the off-chain signature mechanism, usually using Metamask.
It doesn't seem possible to access Metamask from the iframe. it would be great if the SDK could provide a signature method.

Cheers,

**Comment by rmeissner** [comment]
I do agree that this is something we need to add. could you quickly outline why it is not possible to access metamask? Afaik it should inject itself also into the iframes, it is just required to "enable" it again (but I might be wrong on that).

**Comment by vrolland** [comment]
Oh. You are right it was an issue on my side.

Sorry for the trouble.
