### ISSUE TITLE
Use new /multisig-transactions endpoint for txs.getBySafeTxHash

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-apps-sdk#104]
The endpoint we currently use is set to be deprecated in the near future. We need to check how many projects are using it and depending on that make the change.

**Comment by rmeissner** [comment]
Could we refactor this be a custom rpc call that is handled by the interface?

**Comment by mikheevm** [comment]
makes sense, I would always fetch tho and not return a cached one, since there's no guarantee that cached is up-to-date

**Comment by rmeissner** [comment]
Totally fine, I was more referring to the "pending mock transaction" (if that even still exists)
