### ISSUE TITLE
Add method to onboard and web3modal wrappers to check if running as SafeApp

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-apps-sdk#118]
Currently the only way to check if the app is running as a Safe app is to query the safe info again, which potentially tries to connect to the interface again. It would be nicer to have a `isConnectedToSafe` (or similar) method that just checks if it is connected (e.g. by checking the cached safe info).

**Comment by mikheevm** [comment]
added in https://github.com/gnosis/safe-apps-sdk/releases/tag/r8
