### ISSUE TITLE
safe-apps-web3modal fails to compile

### ISSUE THREAD

**Issue by dan13ram** [gnosis/safe-apps-sdk#124]
Hi team,

While trying to integrate `@gnosis.pm/safe-apps-web3modal` into my app. I get the following error:
```
./node_modules/@gnosis.pm/safe-apps-web3modal/dist/index.js
Module not found: Can't resolve './modal' in './node_modules/@gnosis.pm/safe-apps-web3modal/dist'
```
I noticed that this is because the directory at `./node_modules/@gnosis.pm/safe-apps-web3modal/dist` has only one file `index.js`
```
$ ls ./node_modules/@gnosis.pm/safe-apps-web3modal/dist
index.js
```

The package.json I'm using reads as follows:
```
    "@gnosis.pm/safe-apps-sdk": "^2.2.0",
    "@gnosis.pm/safe-apps-web3modal": "^0.2.0",
    "web3modal": "^1.9.3"
```

Please check and release an updated version with a fix. Do let me know if you need any other details.

**Comment by rmeissner** [comment]
Actually the same for the onboard package 🤔

**Comment by mikheevm** [comment]
Thanks for reporting! Versions 0.2.1 for both web3modal/onboard are released now. Sorry for the inconvenience

**Comment by mikheevm** [comment]
https://github.com/gnosis/safe-apps-sdk/pull/125

**Comment by dan13ram** [comment]
Thanks for the quick turnaround! 🙌🏽
