### ISSUE TITLE
Add support for xDai Gnosis Safes

### ISSUE THREAD

**Issue by dan13ram** [gnosis/safe-apps-sdk#128]
Hi team,
I noticed that the provider for xDai Gnosis Safes does not return `chainId`
It is returned as `undefined` as per https://github.com/gnosis/safe-apps-sdk/blob/4fb096ac61b125cdbb7680f65ab990534f9bb0c3/packages/safe-apps-provider/src/provider.ts#L33

I'm not sure what other places needs changes, but please do the needful for supporting xDai Gnosis Safes =)

**Comment by mikheevm** [comment]
should be added in provider version 0.2.4
