### ISSUE TITLE
Use of private fields prevents use of SDK in Vue 3 apps

### ISSUE THREAD

**Issue by TomAFrench** [gnosis/safe-apps-sdk#141]
https://github.com/gnosis/safe-apps-sdk/blob/cb6c4657500ba3f62b89cbefdf3acd1321db2a95/packages/safe-apps-sdk/src/txs/index.ts#L6

Use of the `#variable` syntax causes the SDK to break in situations where the sdk is stored in a proxy as they change the value of `this`. Vue3 uses proxies extensively for state management so this creates a barrier for making Vue apps Safe-compatible.

This could be fixed by switching to the `private variable` syntax  as used in the `SafeAppProvider` (although this comes at the cost of removing runtime enforcement). Alternatively I'd have to maintain a fork which can be used in Vue apps.

Some more info here: https://github.com/tc39/proposal-class-fields/issues/106

**Comment by mikheevm** [comment]
@TomAFrench sorry I forgot to write this a week ago. I'm not super familiar with Vue, but I assume it uses proxies when you use some equivalent of React.js state variables. I don't think it really makes sense to store it there. Once you initialize the SDK, you can use the same instance throughout the app and just put it into a javascript module.
