### ISSUE TITLE
Safe-Apps starter-kit

### ISSUE THREAD

**Issue by nicosampler** [gnosis/safe-apps-sdk#15]
We think it could be a good idea to create a starter-kit, to allow developers to start developing safe-apps as quickly as possible.

We propose to fork `create-react-app` and allow users to install a safe version of it like so: `npx create-react-safe-app`. After running this command, the users will have a TS sapp running, integrated with safe-react-components and the SDK. 

They will only need to deploy it to IPFS/Netlify and the app will show a basic component with the Safe info.

Notes:
- https://create-react-app.dev/docs/custom-templates/
- https://github.com/gnosis/safe-app-template

**Comment by krzysu** [comment]
I just released Gnosis Safe App Starter, it integrates Safe Apps SDK and safe-react-components. It is built with TypeScript and provides `useSafeApp` React hook.

```
const { appsSdk, safeInfo } = useSafeApp();
```

Let me know if you have any ideas for improvements. I'm also happy to transfer this repo to Gnosis if you keep me as a contributor.

See the Gnosis Safe App Starter here https://github.com/krzysu/gnosis-safe-app-starter

**Comment by mikheevm** [comment]
No need to fork anything. Custom templates are supported by CRA: https://create-react-app.dev/docs/custom-templates/

I suggest using @rmeissner or @krzysu project as a template

wdyt?

**Comment by mikheevm** [comment]
WIP repo: https://github.com/gnosis/safe-app-template

**Comment by mikheevm** [comment]
The template is now available on npm https://www.npmjs.com/package/@gnosis.pm/cra-template-safe-app
