### ISSUE TITLE
@safe-apps-sdk - bundle size - consider importing semverGte directly, or remove semver altogether

### ISSUE THREAD

**Issue by brendanmc6** [gnosis/safe-apps-sdk#154]
Semver makes up 58% of this javascript bundle, according to [bundlephobia](https://bundlephobia.com/result?p=@gnosis.pm/safe-apps-sdk@2.3.0).

Semver is only used on one line:
https://github.com/gnosis/safe-apps-sdk/blob/9568ed238b584251ac9ee5e21c5cbbaf1693fc9f/packages/safe-apps-sdk/src/communication/index.ts

Consider importing the function directly for better code-splitting (this probably won't reduce the predicted size on bundlephobia, but may reduce final bundle size for projects with tree-shaking)
```
const semverGte = require('semver/functions/gte')
```

Or even better, compare version by hand and remove semver from `package.json` :)

Not sure if this is high-prio as it's possible the above file is already tree-shaken in most projects, I haven't looked where that file is actually used

**Comment by mikheevm** [comment]
fixed in https://github.com/gnosis/safe-apps-sdk/releases/tag/r8
