### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-apps-sdk#19]
It should be easy to start developing a Safe app by following our documentation. Also we should expose our documentation more (link to developer portal)

### Why would we want this?
We want developers to write Safe apps, therefore we should support them as best as we can.

### Notes?
* Should we make documentation framework-agnostic? Currently the example is written in react

**Comment by mikheevm** [comment]
> Should we make documentation framework-agnostic? Currently, the example is written in react

It's already done.  Docs don't use any react syntax, but example apps are in react
