### ISSUE TITLE
consider @ethvault/iframe-provider

### ISSUE THREAD

**Issue by moodysalem** [gnosis/safe-apps-sdk#191]
https://github.com/ethvault/iframe-provider

some prior art here, and in the polyfill repo, that may be useful to review for differences

**Comment by mikheevm** [comment]
Did you encounter any problems with the current provider or just sharing with us to take a look? 
We don't follow RPC for the communication between the main web app and a safe app, we use our custom API and the current provider is just an ethereum RPC API compatible wrapper on top of our API. The provider was made with https://github.com/pedrouid/eip1193-provider as an example in mind

**Comment by moodysalem** [comment]
asking to take a look, we are considering something like this gnosis safe sdk for widget-izing the interface in a more generic way than just for gnosis safe.

what is the advantage of using a custom api? seems it simply requires more code for both the parent and child window than using a communication protocol that can be forwarded directly to another json rpc provider

**Comment by mikheevm** [comment]
> what is the advantage of using a custom api?

I don't think there's a clear advantage. One weak advantage I can think of is more flexibility/convenience over following eth RPC API when it comes to adding app-specific methods such as transaction exporting, balances, owners, etc (I know that you can add a custom method to the eth RPC api). In case we used an eth provider as the primary backend, we'd have to extend it with app-specific methods, so it's basically just the opposite of what we do now.

> seems it requires more code for both the parent and child window

It's not a lot of code, it's basically just another RPC provider :)

**Comment by mikheevm** [comment]
Also safe itself is not super compatible with eth rpc API, we have different properties in transactions, they're not immediately available because they need to be signed by other owners, etc

**Comment by mikheevm** [comment]
I'm closing this, if you have any further questions feel free to contact us! And thanks for sharing this provider
