### ISSUE TITLE
Check that the SDK works with Vite

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-apps-sdk#244]
https://vitejs.dev/

Vite works only with ESM but we distribute CJS, we should make sure the package works with nextgen tooling

**Comment by mikheevm** [comment]
I created an example app using VIte and it worked just fine: https://github.com/gnosis/safe-test-app/tree/main/vite-test/safe-apps-sdk-vite-test

I tested safe-apps-sdk, safe-apps-react-sdk and safe-apps-provider

**Comment by sakulstra** [comment]
@mmv08 would it still be possible to get a esm bundle?

While most systems nowadays support esm/cjs in combination in a lot of cases(e.g. on the pupular nextjs) safe sdk will bloat the bundle as it will force in a cjs copy of its dependencies (viem) while other packages rely on the esm version.
