### ISSUE TITLE
Exposing connected network information to the safe apps

### ISSUE THREAD

**Issue by yagopv** [gnosis/safe-apps-sdk#254]
## Overview

Currently there is no easy way to retrieve basic network information like the NATIVE_TOKEN info without filtering the safe balances for example. 

## Goals

Having the info would be useful for resolving situations like the exposed in this ticket [gnosis/safe-react-apps#185](https://github.com/gnosis/safe-react-apps/issues/185)

One place to make the improvement could be the `getSafeInfo()` method implemented in safe-react:

https://github.com/gnosis/safe-react/blob/cd89085680db6b3e348efaf40e75574f9fc525f6/src/routes/safe/components/Apps/components/AppFrame.tsx#L184-L190

In the network property we can include more information.  Right now we are only receiving the network name as string

What do you think @mikheevm and @dasanra ?

**Comment by mikheevm** [comment]
It makes sense to me. The only thing I'd change is to add a separate `getNetworkInfo` method instead of including network info in `getSafeInfo` response

**Comment by dasanra** [comment]
Finally we are going to add a new property to the `getSafeInfo` method, returning the chain with the complete network info that we need right now.

This is the minimum information that we need

```
chainInfo: {
  chainName 
  chainId
  shortName
  nativeCurrency
}
```

This naming is aligned with the info we get from the client gateway

**Comment by JagoFigueroa** [comment]
Will be closing this task via https://github.com/gnosis/safe-react-apps/issues/185 ;)
