### ISSUE TITLE
Explore analytics for SDK usage

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-apps-sdk#255]
We don't collect any analytics on what SDK versions are used. Therefore it's tough for us to implement changes because we cannot estimate how many apps it will affect.

**Comment by yagopv** [comment]
Created a doc for different approaches to implement this:

https://docs.google.com/document/d/1oIro4LQnJGFT9Z14Ukb5myKO4EX2M8oDdF17fQh01vs/edit?usp=sharing

**Comment by dasanra** [comment]
@yagopv I was taking a look at the document. I think I agree with method 1, we should add the analytics to the web, also we already have analytic consent there active or not so it won't be a big overhead.

If we go with this approach, how will you pass the SDK version to analytics?

**Comment by dasanra** [comment]
After discusion and the doc with different ways of solving this issue I will add this to draft problem statements so we can properly present the issue to the roadmap planning
