### ISSUE TITLE
The app is loaded outside safe context

### ISSUE THREAD

**Issue by quocanhbk** [gnosis/safe-apps-sdk#265]
I run into this error `The app is loaded outside safe context` while trying to connect using `@gnosis.pm/safe-apps-web3-react` and `@web3-react`.
I'm not using iframe. 
Here's my demo app: https://test-wallet.vercel.app/
And repository: https://github.com/quocanhbk/test-wallet

**Comment by mikheevm** [comment]
Safe apps can be only loaded inside an iframe inside the Safe web application

**Comment by quocanhbk** [comment]
I'm trying to add Gnosis Safe connection just like https://copperlaunch.com/. How can I get rid of that error using `@gnosis.pm/safe-apps-web3-react`.
I did looked into some examples like `cra-template-safe-app`  but it doesn't work (just keep loading forever).
Thanks if you could help.

**Comment by mikheevm** [comment]
If you want to use the dApp outside the Safe web app, you can use the WalletConnect protocol. It's impossible to use the Safe App SDKs without loading the app inside the Safe interface.

**Comment by mikheevm** [comment]
The app already works as a Safe App btw
