### ISSUE TITLE
research & fix deployment

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-apps-sdk#269]
we disabled automated deployments with changesets, and now we need to find an alternative way to do it

**Comment by dasanra** [comment]
In travis time for safe-react-components as I mentioned we had this script to build and send compiled files to a devops managed source
https://github.com/gnosis/safe-react-components/blob/9f718d1dac968a37309f60f6d82b21bebe249eac/.travis.yml#L21

In this line we uploaded to devops repository as we do with static files for web or safe-apps
https://github.com/gnosis/safe-react-components/blob/9f718d1dac968a37309f60f6d82b21bebe249eac/.travis.yml#L71

We could do something similar but on github actions. I know that for safe-react-components the system is still mounted on their side, we should just start using it and ask to them to add also anotherone for safe-apps-sdk

**Comment by mikheevm** [comment]
@dasanra, I'm testing a scenario with changesets because I'd still like to use it to keep track of releases/change descriptions because it's essential given that developer teams are relying on this package. I should have some proposals soon

**Comment by mikheevm** [comment]
@dasanra So without the release step the changesets action doesn't publish releases on github, so I suggest forking the action and adjusting it to our needs, the code is fairly simple: https://github.com/changesets/action/blob/main/src/index.ts

I suggest we just allow to execute a custom command on the release step
