### ISSUE TITLE
Chore. Merge dep-bumps branch from gnosis/safe-react-eslint-plus-action into main

### ISSUE THREAD

**Issue by yagopv** [gnosis/safe-apps-sdk#282]
For finishing the work being done in https://github.com/gnosis/safe-apps-sdk/issues/276 we need to merge [this branch](https://github.com/gnosis/safe-react-eslint-plus-action/tree/feature/dep-bumps) into the main one. 

We need to wait until these repos start using the 3.5.0 or 4.0.0 tags in the main branch for avoid breaking CI/CD workflows

- https://github.com/gnosis/safe-react
- https://github.com/gnosis/safe-react-apps
- https://github.com/gnosis/safe-apps-sdk
- https://github.com/gnosis/safe-react-e2e-tests
- https://github.com/gnosis/safe-react-components
- https://github.com/gnosis/safe-react-gateway-sdk
- https://github.com/gnosis/safe-apps-dev-ui

**Comment by dasanra** [comment]
All projects are already using a fixed version on their main branch

**Comment by mikheevm** [comment]
Just a reminder that I fixed dep bump problems by randomly trying stuff until errors didn't go away. I didn't foresee we would use it as the upstream. That's why I suggested the team explore different actions
