### ISSUE TITLE
Cannot set debug mode

### ISSUE THREAD

**Issue by gabmontes** [gnosis/safe-apps-sdk#284]
The compiled version of the `SafeAppConnector` class seems to have a problem passing call arguments to the constructor as seen in the line below:

https://github.com/gnosis/safe-apps-sdk/blob/4966a34e1d2bcc6f6caac5e25251510bd7c170cc/packages/safe-apps-web3-react/dist/connector.js#L13

It properly passes the arguments to the `AbstractConnector` (call to `super`) but the call in the above referenced line is done with no params at all.

This problem prevents, i.e. calling `new SafeAppConnector({ debug: true })` and properly set `debugMode` in `PostMessageCommunicator`.

It looks like a transpiling/building/bundling (configuration) issue as the .ts code seems correct.

Thoughts?

PS: Tested this by patching the line mentioned above, calling `new safe_apps_sdk_1.default(...arguments)` and debug mode is properly set.

**Comment by yagopv** [comment]
Hi @gabmontes 

We addressed [this](https://github.com/gnosis/safe-apps-sdk/pull/286), so if you use @gnosis.pm/safe-apps-web3-react@1.0.0 debug mode should work as expected
