### ISSUE TITLE
`onSafeInfo` is triggered in a loop

### ISSUE THREAD

**Issue by krzysu** [gnosis/safe-apps-sdk#38]
When I use `onSafeInfo` as recommended in your docs, my react app gets in a render loop. It didn't happen with the previous version (0.1.1) of the SDK. I don't know when exactly the bug was introduced, last time I built a Safe App, I used SDK v0.1.1.

Compare these code samples:

With SDK 0.3.1 this code logs 'render' and 'onSafeInfo' in never ending loop

```
  const [appsSdk] = useState(initSdk());
  const [safeInfo, setSafeInfo] = useState<SafeInfo>();

  console.log("render");

  useEffect(() => {
    appsSdk.addListeners({
      onSafeInfo: (info) => {
        console.log("onSafeInfo");
        setSafeInfo(info);
      },
    });

    return () => appsSdk.removeListeners();
  }, [appsSdk]);
```

so I have to add an extra check, which was not necessary in v0.1.1

```
  const [appsSdk] = useState(initSdk());
  const [safeInfo, setSafeInfo] = useState<SafeInfo>();

  console.log("render");

  useEffect(() => {
    appsSdk.addListeners({
      onSafeInfo: (info) => {
        console.log("onSafeInfo");
        if (!safeInfo) {
          setSafeInfo(info);
        }
      },
    });

    return () => appsSdk.removeListeners();
  }, [appsSdk, safeInfo]);
```

Could you check and advise?

**Comment by mikheevm** [comment]
As I understood the repo for reproducing is https://github.com/krzysu/gnosis-safe-app-starter

It looks like there's a problem with SafeAppProvider which makes `initSdk` called multiple times. And each time SDK sends initialization event, the interface sends safe information in the response

Moving `initSdk` outside `SafeAppProvider` fixed the issue for me.

**Comment by mikheevm** [comment]
Good job on the starter btw, are you planning to make this a lib? So the hook is exported

**Comment by mikheevm** [comment]
Oh, what interface version were you using? I think I totally missed it when reproducing

**Comment by krzysu** [comment]
@mikheevm I don't plan to make it as lib as I don't want to maintain it :) Maybe it could be a part of `safe-apps-sdk`? Or it should be a new lib like `react-safe-apps-sdk` that exposes `SafeAppProvider.tsx` and `useSafeApp` hook.

**Comment by krzysu** [comment]
Do you mean, which version of SDK I was using? I had an issue with 0.3.1 (connecting to Safe deployed at https://gnosis-safe.io/app) but it worked fine for me with previous older version 0.1.1.

**Comment by mikheevm** [comment]
@krzysu no, the interface version (rinkeby.gnosis-safe.io or something else)

**Comment by krzysu** [comment]
I had that issue for both rinkeby.gnosis-safe.io and mainnet https://gnosis-safe.io/app. Initializing SDK outside of React component helps though.
