### ISSUE TITLE
Error while running vanilla CRA template

### ISSUE THREAD

**Issue by chrisciszak** [gnosis/safe-apps-sdk#75]
When running the current CRA template from scratch the app doesn't load and I keep getting the error below in the Safe-React app:

ThirdPartyApp: A message was received without message id.

Any idea what's wrong?

**Comment by rmeissner** [comment]
Which version of the cra template is used?

**Comment by chrisciszak** [comment]
The current one 2.0. 

I assume the problem comes from running a custom Safe-React app( version 2.15.1) which was not upgraded to the latest 2.17?

**Comment by mikheevm** [comment]
what version of the interface are you using?

**Comment by mikheevm** [comment]
I have just tested it by running
```
npx create-react-app my-safe-app-v1 --template @gnosis.pm/cra-template-safe-app
```

and then the app worked perfectly fine (Loaded, an address is shown with a submit button for dumb tx) on safe-react development branch

I assume you're using the old version of the interface (I guess you're running it locally), the new SDK is not backward compatible with older versions of the interface, so just do
```
git pull origin master
```
and it should work :)

**Comment by rmeissner** [comment]
Yes the latest version of the sdk is only compatible with the latest version of the interface. The older version of tge sdk will also work with the new interface version.

We recommend using the new sdk as we will not backport features (e.g. being able to route reading rpc calls through the interface, therefore removing the requirment of your own rpc endpoint)

**Comment by chrisciszak** [comment]
Upgrading the Safe-React app to the latest version fixed the problem! Thanks for the quick responses and awesome work on the sdk.
