### ISSUE TITLE
NODE_ENV=production yarn start — Uncaught SyntaxError: Unexpected token '<' — Manifest: Line: 1, column: 1, Syntax error.

### ISSUE THREAD

**Issue by stefek99** [gnosis/safe-apps-sdk#81]
`yarn start` - works for me

`NODE_ENV=production yarn start` - fails

![image](https://user-images.githubusercontent.com/249703/104316125-ea42a180-54d3-11eb-8fa9-47d47e53d521.png)

Everything else is the same.

### What are you actually trying to do?

```
if (production) {
  contractAddress = 0xABC..
} else if (dev) {
  contractAdress = 0xDEF...
}
```

https://riptutorial.com/node-js/example/10101/setting-node-env--production-

And this https://stackoverflow.com/questions/37885952/export-in-an-if-statement-using-meteor
> "Exports must be defined at the top level (from §A.5 of the spec). This is related to how modules are handled when lazy-loading or circular dependencies occur and the code can't be executed during or before loading."
> "Exporting a function able to decide is a far more robust solution."

The trouble that I have: `NODE_ENV=production` does not allow thing to start at all :(

**Comment by mikheevm** [comment]
Are you using cra-template-safe-app?

**Comment by mikheevm** [comment]
It looks like `react-app-rewired` tool we're using internally to build doesn't support such scenario.

For now, you can build the production bundle and serve it locally by using, for example, [serve](https://www.npmjs.com/package/serve):
```
npm run build && cd build && serve -s -d
```

**Comment by stefek99** [comment]
I think I found workaround, took me a while

```
PORT=3010
HTTPS=true
REACT_APP_INFURA_ID=hacker
STRING=empty
REACT_APP_STRING=empty too?
```

The stuff in `.env` should have `REACT_APP_...` prefix.

Obvious once you know it.
