### ISSUE TITLE
Add CLA to repository

### ISSUE THREAD

**Issue by germartinez** [gnosis/safe-apps-sdk#84]
As we value 3rd party contributions (and more have been coming in), please coordinate to add the cla assistent to all of our repos. You can find an example in the safe-react repo: https://github.com/gnosis/safe-react/blob/development/.github/workflows/cla.yml Also make sure not to merge contributions of external devs before this is in place please

**Comment by mikheevm** [comment]
Why was this closed?

**Comment by germartinez** [comment]
Sorry, I was closing some issues and clicked too fast on this one. It's now reopened.
