### ISSUE TITLE
Allow to disable logging

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-apps-sdk#86]
Currently we log every incomming message, this massively polutes the logs and makes it hard to see the logs for devs

**Comment by mikheevm** [comment]
Chrome DevTools have really great filtering abilities. Do we really need that?

**Comment by rmeissner** [comment]
I could not get them filtered out. The logs from the sdk are `info` and from the same host ... so now my app logs all need to use `warn` or I need to add a filter with regex ... it is not user friendly. By default I would disable logs or allow to provide a custom logger.
