### ISSUE TITLE
Add a method for requesting safe token balances from tx service

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-apps-sdk#94]
One of the app developers struggled with that a little bit, I think it would be great to expose a method that would use `GET /balances` endpoint from tx service

**Comment by rmeissner** [comment]
I am a bit hestitant about adding more direct communication with the services. At some point we do want to authenticate them and then all this potentially doesn't work anymore.

**Comment by mikheevm** [comment]
But if a dapp developer uses it directly it will stop working too, won't it? 😀

**Comment by rmeissner** [comment]
yes ... so we need to provide an alternative that doesn't directly use our endpoints or they need to uses other service providers.

**Comment by mikheevm** [comment]
> yes ... so we need to provide an alternative that doesn't directly use our endpoints or they need to uses other service providers.

Any ideas what it can be? A 3rd party API?

**Comment by rmeissner** [comment]
I would route everthing through the communication with the interface. The interface is authorized and has cached information and the safe apps should not have to connect to some other service.
